version: '3.8'

services:
  chat-app:
    image: chat-app
    container_name: chat-app-container
    ports:
      - 8080:3000

  nginx:
      build: 
          context: ./nginx
      ports:
        - 80:80
      depends_on:
        - chat-app
      restart: always