apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.nameOverride}}
  namespace: {{.Values.namespaceName}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.nameOverride}}
  template:
    metadata:
      labels:
        app: {{.Values.nameOverride}}
    spec:
      containers:
        - name: {{.Values.nameOverride}}-container
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.imagePullPolicy}}
          ports:
            - containerPort: {{.Values.containerPort}}
          resources:
            requests:
              cpu: {{.Values.requests.cpu}}
              memory: {{.Values.requests.memory}}
            limits:
              cpu: {{.Values.limits.cpu}}
              memory: {{.Values.limits.memory}}
      restartPolicy: {{.Values.restartPolicy}}