apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{.Values.nameOverride}}-issuer
  namespace: {{.Values.namespaceName}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: zakirhasan1109022@gmail.com
    privateKeySecretRef:
      name: {{.Values.nameOverride}}-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: {{.Values.ingressClassName}}