apiVersion: v1
kind: Service
metadata:
  name: {{.Values.nameOverride}}-service
  namespace: {{.Values.namespaceName}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.nameOverride}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.containerPort}}