replicaCount: 3
nameOverride: "chat-app-helm"
namespaceName: "zakir-helm"
containerPort: 3000

image:
  repository: zakir22/chat-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
 type: ClusterIP
 port: 80

requests:
  cpu: 250m
  memory: 256Mi
limits:
  cpu: 500m
  memory: 512Mi
restartPolicy: Always

secret:
  secretName: chat-app-cert-helm

ingressClassName: nginx
host: rapid-app.rfft.nl
path: /
pathType: Prefix






